on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Go
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up Go
      id: go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - name: Test
      run: go test ./...
